### ISSUE TITLE
Can't extract reddit image / Crashes whilst downloading

### ISSUE THREAD

**Issue by Jalawoud** [MalloyDelacroix/DownloaderForReddit#183]
*Issues marked with the **Need Information** label will be closed after 30 days if additional information is not provided*
I am on the latest 3.5 version, on my first few download attempts it would tell me it couldn't extract reddit image / unable to contact server and run for a long time. Now running download just causes it to crash after 5 seconds. My internet connection is perfectly fine. I have the imgur key set up. 

[DownloaderForReddit.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/5652643/DownloaderForReddit.log)

**Comment by MalloyDelacroix** [comment]
It looks like the crashes you're experiencing now are due to trying to download user posts sorted by "rising", which is not a supported sort method for users.  This was fixed in the last update and you are no longer able to select this sort method in the settings.  My guess is that this is hanging around in your settings for these users.

To fix this: Open the settings dialog for the list which contains these users (right click the list selection combo, then click List Settings).  Make sure the Cascade changes checkbox at the top is checked, then scroll down to the "Sort Posts By" combo and change it to any method you like (if it is already set on the one you want, change it to something else, then change it back) and  click OK at the bottom.  This should solve the problem.

The issue with reddit images not extracting looks to be because the content has been deleted from reddit.

The server connection errors are reporting a 403 - forbidden response.  This means that the hosting website has refused to authorize the request for some reason.  It could be that it is behind a paywall or that the website just doesn't allow downloads.  This isn't an app error, but it will not be able to download this content.

**Comment by Jalawoud** [comment]
![image](https://user-images.githubusercontent.com/54126146/101512846-7992ed00-3949-11eb-87a1-c7eefbd362d1.png)


Just to clarify, this is the settings page you are referring to correct? This is the only panel which shows me "cascade", I change "Sort posts by" from "Hot" to "New" yet it still crashes. 

[DownloaderForReddit.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/5660503/DownloaderForReddit.log)


![image](https://user-images.githubusercontent.com/54126146/101513061-bc54c500-3949-11eb-8262-de21dc0cfc55.png)

This is the Users settings I have, if that helps.

**Comment by MalloyDelacroix** [comment]
That is the correct settings page, but you have the "master list" selected, not the list which contains the users you are trying to download.  On that same page on the inside left pane, select "Default [USER]" then try changing the sort method again.

**Comment by Jalawoud** [comment]
This has solved my issue, thank you.

**Comment by Jalawoud** [comment]
Sorry I have one last question, after going to a subreddit folder and moving all of its contents, i proceed to then redownloaded the contents, but the program says download complete with 0 items downloaded. I have already changed the sorting multiple times. This problem only exists with subreddit downloads. 
[DownloaderForReddit.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/5706691/DownloaderForReddit.log)

**Comment by MalloyDelacroix** [comment]
The app doesn't check the download folder for duplicates but instead checks the database for URLs that have already been downloaded.  If you want to re-download content, you need to open the user/subreddit or list settings and uncheck "Avoid Duplicates" and "Limit by Date".  

Alternatively, if you do not want any of the data in the database, it may be easier to delete the database file.  It can be found in the data directory which can be found quickly using the file menu.

**Comment by Jalawoud** [comment]
Ahh okay so I have managed to redownload an entire subreddit, I did this to double check and it seems that most posts aren't downloading with sound. For example, and please excuse the example https://www.reddit.com/r/BundleOfBrittany/comments/9hd77r/dancing_in_bathroom_with_sound_so_you_can_hear/
I believe this is a regular video hosted on reddit.
